# encoding: utf-8

ruby "1.9.3"

source "https://rubygems.org"

# Infrastructure.
gem "nake"
gem "foreman"

# Server-related.
gem "thin"

gem "sinatra"

# Debugging-related.
gem "pry"

# MongoDB.
gem "mongo"
gem "bson_ext"

# E-mails.
gem "pony"

# Vagrant.
group(:vagrant) do
  gem "vagrant"
end

# Test-related.
group(:test) do
  gem "rspec"
end
